### ISSUE TITLE
Investigate using Vitest in combination with Effect as testing setup

### ISSUE THREAD

**Issue by schickling** [Effect-TS/core#1063]
I really like the Vite-backed "HMR" system applied to testing workflows as demonstrated here: https://twitter.com/antfu7/status/1468233216939245579

We should investigate how [Vitest](https://vitest.dev) can be used in Effect projects. 

I'm currently running in the following problems:

- [ ] Effect should use fully qualified import paths (e.g. `import {} from './some-file.js'` instead of `import {} from './some-file'`). Possibly related to https://github.com/vitest-dev/vitest/issues/202
  <img width="1036" alt="image" src="https://user-images.githubusercontent.com/1567498/151028407-b1ec2bcb-1459-4e64-9058-22257da7f2ad.png">
- [ ] Effect currently relies on running `tsc` for the sake of applying the tsc-plugin. This massively slows down the refresh cycle.

**Comment by mikearnaldi** [comment]
The following isn't correct:

```
Effect currently relies on running tsc for the sake of applying the tsc-plugin. This massively slows down the refresh cycle.
```

Effect doesn't rely on any compiler plugin, if you want features like tracing and optimization the compiler plugin is a non avoidable requirement given that the functionality relies on knowledge of the types but if you don't care about those features you can compile using any tool.

As of the first point, adding the `js` extension, it is a major change that is already in the workings for the `next` release and will be addresses in the compiler extension, probably won't happen in current unless we manage to find a quick solution

**Comment by mikearnaldi** [comment]
Resolved in recent releases
