### ISSUE TITLE
Rename `Option.alt` to `Option.orElse`

### ISSUE THREAD

**Issue by schickling** [Effect-TS/core#1133]
IMO the name combinator name `Option.alt` is confusing/unintuitive and I suggest renaming the combinator to `Option.orElse`.

**Comment by wesselvdv** [comment]
I also believe this is on par with what it's called in ZIO (2).

**Comment by IMax153** [comment]
Closing this given it will be resolved after alpha release of the next version of Effect, which delegates to `Option` in `@tsplus/stdlib` (where we have renamed `Option.alt` to `Option.orElse` 😃
