### ISSUE TITLE
Provide Has in Legacy to smooth migration

### ISSUE THREAD

**Issue by mikearnaldi** [Effect-TS/core#317]
In legacy `Service` was used to enable minor derivation of utility functions, in general TS 4 made it impossible to use recursive constraints in interface definitions and that 'broke' service.

For the next major `Has` & `Tag` have been designed to smoothly embed services in context and that can be backported to legacy to allow a migration path to happen.

**Comment by mikearnaldi** [comment]
TS version has been updated in legacy to 4.0 and self recursive types have been removed, missing still Has/Tag for migration (also thinking about a compatibility layer to interop the 2 effect systems)

**Comment by patroza** [comment]
Hard to imagine this would still be desired, if no one spoke up so far..
