### ISSUE TITLE
Support ESM Restrictions for Modules

### ISSUE THREAD

**Issue by mikearnaldi** [Effect-TS/core#773]
Webpack and other bundlers make assumptions when treating ESM modules that modules can be duplicated, effect modules usually require stateful operations (like `tag`, `tracing`, `fiberIds`, etc) that are not compliant with the assumption.

Webpack suggests a very impractical workaround of creating ESM wrappers for stateful modules that re-export CommonJS, while this is possible for contained use cases it is quite dumb for general usage as every single file of effect code will have tags and stuff like that so every single module would need wrappers (including app code).

**Comment by mikearnaldi** [comment]
The design of `tag` could be: in `core` the `tag` function will require explicit `PropertyKey` to be specified and usage should be like:

```ts
const Service = tag<Service>(Symbol.for("@module/Service"))
```

With the `fluent` package we could provide an overload where `Symbol.for("@module/Service")` gets automatically filled by the compiler plugin in.

**Comment by mikearnaldi** [comment]
Classes compared using `instanceof` are also problematic, we should minimize class usage in favor of plain objects and revise `Case` and similar to avoid usage of `instanceof`

**Comment by mattiamanzati** [comment]
That's actually a shame, lots of instances where classes shine a lot. Maybe we can introduce a symbol method that acts as intanceof operator, and then use tagged classes?

**Comment by mikearnaldi** [comment]
yeah it's really not about not using classes rather avoiding instanceof. For symbols we still need a solution to avoid manual `.for(id)`

**Comment by mikearnaldi** [comment]
> @mikearnaldi Perhaps you could utilize `.constructor === Foo` to avoid instanceof? https://www.measurethat.net/Benchmarks/Show/13797/0/instanceof-vs-string-comparison-vs-property-checking-vs

would have exactly the same problem, with eventual module duplication you can't rely on constructor to identify
