### ISSUE TITLE
Improve stack traces for unhandled/unmanaged JS errors

### ISSUE THREAD

**Issue by schickling** [Effect-TS/core#870]
![image](https://user-images.githubusercontent.com/1567498/134480634-5539fc31-f8ec-452a-abb8-974807e2884d.png)

Context from Discord:

<img width="914" alt="image" src="https://user-images.githubusercontent.com/1567498/134480686-9cf4f69d-c464-49fa-a837-d7ed14f91926.png">

**Comment by mikearnaldi** [comment]
Done with the new tracing coming to the RC, while it is not possible to scope the error to the precise line the stack trace and execution trace will contain the closest gen.

Note that the precise line in case of exceptions can be found in the stack of the error:

![Screenshot 2022-11-01 110849](https://user-images.githubusercontent.com/24249610/199220269-f439a9ed-c613-49bb-b6a5-d683c093fe0b.png)
