### ISSUE TITLE
Consider renaming utility type `_A` to something more descriptive

### ISSUE THREAD

**Issue by schickling** [Effect-TS/core#963]
<img width="546" alt="image" src="https://user-images.githubusercontent.com/1567498/142725749-0ea1737a-3426-4e9c-bb2d-490ad4cabf39.png">

**Comment by wesselvdv** [comment]
Maybe something along the lines of ExtractA?

**Comment by mikearnaldi** [comment]
I've tried many names `OutputOf`, `ExtractOut` etc, they are all, in my opinion, far too long and they get stranger in data types with more parameters, I find it easy to remember `to extract A use _A, to extract E use _E, to extract * use _*`

**Comment by mikearnaldi** [comment]
One of the issue in giving "proper" name is also that "_A" is totally generic, it isn't related to effect it just extracts `A` from `{ _A: () => A }` this is done so it can work fine with every data type that has that field (Effect, Managed, Stream, etc) what we could do is to export named alias for every module like `T.ExtractOutput` , `T.ExtractError`, `S.ExtractElement`, etc, not removing (nor renaming) the generic ones (_A,_E,etc)

**Comment by wesselvdv** [comment]
I do agree with you on the _A convention, it took me a while to figure out that I could extract all A using this. (effect, managed, etc) but now that I know, it’s pretty easy to work with it.

**Comment by isthatcentered** [comment]
`fp-ts` provides a [conventions page](https://gcanti.github.io/fp-ts/guides/code-conventions.html) to address those kinds of questions. Maybe `effect-ts` could have something similar?

(Technically reading the `dev.to` articles also does the trick but that might be asking a bit much of newcomers)

**Comment by mikearnaldi** [comment]
For next release they will be aliases in each module's namespace, i.e. for `Effect` you will have `Effect.Success`, `Effect.Error`, `Effect.Context`.
