### ISSUE TITLE
Intellij - Autosuggestion not working without explicit @effect-ts/system install

### ISSUE THREAD

**Issue by isthatcentered** [Effect-TS/core#998]
In Intellij Idea  typescript only detects the direct exports from `@effect-ts/core/effect`, not the re-exported modules from `@effect-ts/system` (See below)

Without explicit install only direct exports are found:
![341F72A9-08DA-4457-A97F-A5FB1E0BDB35](https://user-images.githubusercontent.com/10481124/145823438-9e2f4b7d-3559-431c-bf97-52f06057f7ca.png)

With explicit install, re-exports from system are found:
![037CDA49-2222-4D4C-B0AF-F19ACB2066D0](https://user-images.githubusercontent.com/10481124/145823649-e19d723d-c47f-4ca3-be07-1fd6907ca037.png)

## Debug:
- The dependency `@effect-ts/system` is  indeed installed
- Autosuggestion works fine in vs code
- I haven't had this problem with any other package but `effect-ts` relies heavily on re-exports
- Deps: `@effect-ts/core (latest)  typescript (4.5.2)`

## Possible Solutions
Simply add the package as an explicit installation in the `Readme` "How to install" section. 
Drawbacks: 
- Freezes the dependency on `system` which could hurt later if you plan on changing how things work
- Won't hurt anyone but this is solving a few people's problem by making everybody "pay"
Advantages:
- Won't hurt anybody 🤷‍♂️

I haven't been able to solve the issue any other way (editor config) for now. 

If this works for you the PR #1004 is already opened :)

**Comment by MartinRamm** [comment]
I ran across this problem as well today. I have created a bug report with intellij, as this is not a problem with effect, but rather of the ide: https://youtrack.jetbrains.com/issue/WEB-62911/Imports-from-subdependency-not-resolved-autosuggest-not-working
